name: hdiff
version: 0.0.5
synopsis: Pattern-Expression-based differencing of arbitrary types.
description: This package provides an executable and a library to compute
  and manipulate pattern-expression based differences between
  values of arbitrary datatypes. For more detailed information
  check the README at our GitHub page.
author: Jort van Gorkum <jortvangorkum@gmail.com> & Victor Miraldo <v.cacciarimiraldo@gmail.com>
maintainer: Jort van Gorkum <jortvangorkum@gmail.com>
github: jortvangorkum/hdiff
category: Other

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - cryptonite
  - containers
  - mtl
  - prettyprinter
  - prettyprinter-ansi-terminal
  - text
  - memory
  - template-haskell
  - deepseq
  - simplistic-generics

internal-libraries:
  hdiff-lib:
    source-dirs: src/hdiff
    ghc-options: -O2 -Wall

library:
  source-dirs: src/incremental
  dependencies:
    - hdiff-lib

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - QuickCheck
      - hspec
      - hdiff-lib

executables:
  hdiff:
    source-dirs:
      - executable/hdiff
    main: HDiff.hs
    dependencies:
      - parsec
      - gitrev
      - optparse-applicative
      - language-lua
      - language-java
      - language-ecmascript
      - language-bash
      - language-python
      - time
      - deepseq
      - hdiff-lib
    # cpp-options: -DREAL_LANGUAGES
    ghc-options: -XCPP -O2 -Woverlapping-patterns -Winaccessible-code -Wincomplete-patterns -Wincomplete-uni-patterns -Wincomplete-record-updates
