name: incremental-hdiff
version: 0.1.0.0
github: "githubuser/incremental-hdiff"
author: Jort van Gorkum <jortvangorkum@gmail.com>
maintainer: Jort van Gorkum <jortvangorkum@gmail.com>
copyright: "2021 Jort van Gorkum"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jortvangorkum/hdiff#readme>

dependencies:
  - base >= 4.7 && < 5
  - hdiff
  - parsec
  - simplistic-generics
  - mtl
  - optparse-applicative
  - deepseq

library:
  source-dirs: src

executables:
  incremental-hdiff-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - incremental-hdiff

tests:
  incremental-hdiff-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - hspec
      - incremental-hdiff
