name: HDiff GitHub Actions
on: [push]
jobs:
  runhaskell:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        ghc-version: 8.6.5
        cabal-version: 'latest'
        stack-version: 'latest'
    - name: Cache Stack
      uses: actions/cache@v2
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
    - run: stack build
    - run: stack test