name: HDiff GitHub Actions
on: [push]
jobs:
  linting-haskell:
    name: Linting Haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check stylish-haskell and hlint
        run: |
          curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s incremental-hdiff
          curl -sSL https://raw.github.com/jaspervdj/stylish-haskell/master/scripts/latest.sh | sh -s $(find . -type f -name "*.hs" ! -path "*.stack-work*" ! -path "*executable*") -i
          if [ -z "$(git status --porcelain)" ]; then
              echo "No style errors detected."
          else
              echo "Style errors detected:"
              git --no-pager diff
              exit 1
          fi

  runhaskell:
    name: Build and Test
    needs: linting-haskell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          enable-stack: true
          ghc-version: 8.6.5
          cabal-version: "latest"
          stack-version: "latest"
      - name: Cache Stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack
            hdiff/.stack-work
            incremental-hdiff/.stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('hdiff/stack.yaml.lock', 'hdiff/package.yaml', 'incremental-hdiff/stack.yaml.lock', 'incremental-hdiff/package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack
      - name: Stack build and test HDiff
        run: |
          cd hdiff
          stack build
          stack test
      - name: Stack build and test Incremental HDiff
        run: |
          cd incremental-hdiff
          stack build
          stack test
