name: HDiff GitHub Actions
on: [push]
jobs:
  runhaskell:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        ghc-version: 8.6.5
        cabal-version: 'latest'
        stack-version: 'latest'
    - name: Cache Stack
      uses: actions/cache@v2
      with:
        path: | 
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack
    - run: stack build
    - run: stack test